server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: exams-application
          uri: lb://EXAMS
          predicates:
            - Path=/exams/**
        - id: uploader-application
          uri: lb://UPLOADS
          predicates:
            - Path=/upload/**
        - id: tasks-application
          uri: lb://TASKS
          predicates:
            - Path=/tasks/**
        - id: profile-application
          uri: lb://PROFILE
          predicates:
            - Path=/profile/**
    discovery:
      locator:
        enabled: true
          
