server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: exams-application
          uri: lb://EXAMS
          predicates:
            - Path=/examsV1/**
        - id: uploader-application
          uri: lb://UPLOADS
          predicates:
            - Path=/uploadsV1/**
        - id: tasks-application
          uri: lb://TASKS
          predicates:
            - Path=/tasksV1/**
        - id: profile-application
          uri: lb://PROFILE
          predicates:
            - Path=/profileV1/**
    discovery:
      locator:
        enabled: true
          
