server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: exams-application
          uri: http://localhost:9001
          predicates:
            - Path=/exams/**
        - id: uploader-application
          uri: lb://UPLOADER-APPLICATION
          predicates:
            - Path=/upload/**
        - id: tasks-application
          uri: lb://TASKS-APPLICATION
          predicates:
            - Path=/tasks/**
        - id: profile-application
          uri: lb://PROFILE-APPLICATION
          predicates:
            - Path=/profile/**
          
