server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      routes:
        - id: exams-application
          uri: lb://EXAMS-APPLICATION
          predicates:
            - Path=/exams/**
        - id: uploader-application
          uri: lb://UPLOADER-APPLICATION
          predicates:
            - Path=/upload/**
        - id: tasks-application
          uri: lb://TASKS-APPLICATION
          predicates:
            - Path=/tasks/**
        - id: profile-application
          uri: lb://PROFILE-APPLICATION
          predicates:
            - Path=/profile/**
          
