server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://192.168.1.53:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: exams-application
          uri: lb://EXAMS
          predicates:
            - Path=/examsV1/**
        - id: uploader-application
          uri: lb://UPLOADS
          predicates:
            - Path=/uploadsV1/**
        - id: tasks-application
          uri: lb://TASKS
          predicates:
            - Path=/tasksV1/**
        - id: profile-application
          uri: lb://PROFILE
          predicates:
            - Path=/profileV1/**
        - id: security-application
          uri: lb://SECURITY
          predicates:
            - Path=/securityV1/**

discovery:
  locator:
    enabled: true
